# WARNING: this file is not suitable for production, please use with caution
version: '3.9'

services:
  web:
    image: ecommerce
    build: .
    command: flask run -h 0.0.0.0
    env_file:
      - ./.env
    volumes:
      - ./ecommerce:/code/ecommerce
      - ./db/:/db/
    ports:
      - "5000:5000"

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'app']
      interval: 3s
      timeout: 2s
      retries: 3

volumes:
  postgres-data: